### ISSUE TITLE
Ambiguity in 'upstream' and 'downstream' terminology in peak-centric output

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/RnaChipIntegrator#40]
The text for U/D in the documentation and spreadsheet notes is currently:

```
'U' if hit is upstream, 'D' if downstream, '.' if overlapped
```

@IanCodes suggests revising to:

```
'U' if peak is upstream (5') of gene; 'D' if peak is downstream (3') of gene; ' . ' if overlapping
```

**Comment by IanCodes** [comment]
My problem with the kit text is that I can never remember whether "hit"
being U or D is left or right of a gene (on a forward strand example).

**Comment by pjbriggs** [comment]
Hi @IanCodes yes I can see the confusion with the default text and would still like to fix this, but first I need to understand myself what the correct text should be for the different situations.

So my understanding is:

* **Peak-centric analysis**:
  - Gene is upstream (5') of peak if gene position > peak position on + strand;
  - Gene is upstream (5') of peak if gene position < peak position on - strand;
  - Gene is downstream (3') of peak if gene position < peak position on + strand;
  - Gene is downstream (3') of peak if gene position > peak position on - strand.

* **Gene-centric analysis**:
  - Peak is upstream (5') of gene if peak position > gene position on + strand;
  - Peak is upstream (5') of gene if peak position <  gene position on - strand;
  - Peak is downstream (3') of gene if peak position <  gene position on + strand;
  - Peak is downstream (3') of gene if peak position > gene position on - strand.

Is this correct?

**Comment by IanCodes** [comment]
I think you have upstream and downstream swapped.  On the +strand something
that is 5' of the current position is upstream, ie a lower number is
upstream to a higher coordinate number.

Ian

**Comment by pjbriggs** [comment]
@IanCodes thanks, that's immensely helpful - and yes I've got it the wrong way around as you say (also in the process making your point that the description text needs updating/clarifying).

So the correct way around is:

* **Peak-centric analysis**:
  - Gene is upstream (5') of peak if gene position < peak position on + strand;
  - Gene is upstream (5') of peak if gene position > peak position on - strand;
  - Gene is downstream (3') of peak if gene position > peak position on + strand;
  - Gene is downstream (3') of peak if gene position < peak position on - strand.

* **Gene-centric analysis**:
  - Peak is upstream (5') of gene if peak position < gene position on + strand;
  - Peak is upstream (5') of gene if peak position >  gene position on - strand;
  - Peak is downstream (3') of gene if peak position >  gene position on + strand;
  - Peak is downstream (3') of gene if peak position < gene position on - strand.

**Comment by IanCodes** [comment]
Correct! :)

**Comment by pjbriggs** [comment]
Thanks @IanCodes!

I've made some updates to the description of `direction` in the output spreadsheet (in PR #54) and made a first attempt to explain how to interpret "upstream" and "downstream" in the docs (PR #55).

For this latter update, could you have a look at
http://rnachipintegrator.readthedocs.io/en/issue40-add-upstream-downstream-explanation/outputs.html#interpreting-upstream-and-downstream
and let me know what you think - I'm not sure if it's clear, or whether I've understood the 3'/5' concepts correctly, so any feedback is welcome.

**Comment by pjbriggs** [comment]
Final updates (for now) committed and merged into `devel` branch, so closing this as 'done'.
